syntax = "proto3";

message Hello {
    uint32 sender_port = 1;
}

message LinkStateNeighbor {
    bytes node_id = 1;
    uint32 local_port = 2;
    uint32 remote_port = 3;
}

message LinkState {
    repeated LinkStateNeighbor neighbors = 1;
}

message Ack {
    bytes acknowledged_node_id = 1;
    fixed32 acknowledged_boot_id = 2;
    uint32 acknowledged_sequence = 3;
}

message GatewayHello {}

message NetworkPacket {
    bytes source_node_id = 1;
    fixed32 boot_id = 2;
    uint32 sequence = 3;

    oneof payload {
        Hello hello = 4;
        LinkState link_state = 5;
        Ack ack = 6;
        GatewayHello gateway_hello = 7;
    }
}
